# Netlify configuration for LetMeGlowUp
[build]
  publish = "."
  command = "echo 'No build step needed for static HTML'"

[dev]
  command = "npx serve ."
  port = 8888

[template.environment]
  GA_MEASUREMENT_ID = ""
  ADS_CONVERSION_ID = ""
  SENTRY_DSN = ""

# Enable Netlify Forms
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Redirects for SPA routing and clean URLs
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/affiliate-products"
  to = "/affiliate-products.html"
  status = 200

# Netlify Forms handling (auto-detects <form> with netlify attribute)
# Example: <form name="contact" netlify>

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://cdn.tailwindcss.com https://unpkg.com https://browser.sentry-cdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.example.com https://sentry.io https://www.google-analytics.com;"

# Cache optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
